### ISSUE TITLE
`diesel_async::RunQueryDsl` is not implemented for `diesel::SqlQuery`

### ISSUE THREAD

**Issue by xiaoas** [weiznich/diesel_async#77] opened 2023-05-08 03:15 UTC
### Versions

- **Rust:** 1.69.0
- **Diesel:** 2.0.4
- **Diesel_async:** 0.2.2
- **Database:** mysql
- **Operating System** linux

### Feature Flags

- **diesel:** `["mysql", "64-column-tables"]`
- **diesel_async:** `["mysql", "bb8", "tokio"]`

## Problem Description
```rust
use diesel_async::RunQueryDsl;
diesel::sql_query("select version();")
        .load::<String>(&mut conn_result)
```
does not compile.

### What are you trying to accomplish?
I wish to run a raw query to see if diesel_async is working

### What is the expected output?
The code should compile?

### What is the actual output?
``` rust
error[E0277]: the trait bound `Untyped: CompatibleType<std::string::String, Mysql>` is not satisfied
  --> examples/channel.rs:16:10
   |
16 |         .load::<String>(&mut conn_result)
   |          ^^^^ the trait `CompatibleType<std::string::String, Mysql>` is not implemented for `Untyped`
   |
   = help: the trait `CompatibleType<U, DB>` is implemented for `Untyped`
   = note: required for `SqlQuery` to implement `diesel_async::methods::LoadQuery<'_, _, std::string::String>`

error[E0277]: the trait bound `Untyped: CompatibleType<std::string::String, Mysql>` is not satisfied
   --> examples/channel.rs:16:25
    |
16  |         .load::<String>(&mut conn_result)
    |          ----           ^^^^^^^^^^^^^^^^ the trait `CompatibleType<std::string::String, Mysql>` is not implemented for `Untyped`
    |          |
    |          required by a bound introduced by this call
    |
    = help: the trait `CompatibleType<U, DB>` is implemented for `Untyped`
    = note: required for `SqlQuery` to implement `diesel_async::methods::LoadQuery<'_, _, std::string::String>`
note: required by a bound in `diesel_async::RunQueryDsl::load`
   --> /home/xiaoqilin/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/diesel-async-0.2.2/src/run_query_dsl/mod.rs:330:15
    |
330 |         Self: methods::LoadQuery<'query, Conn, U> + 'query,
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `RunQueryDsl::load`
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/weiznich/diesel_async/issues) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2023-05-08 06:02
This is expected behavior as [`sql_query` query results need to be deserialized](https://docs.diesel.rs/2.0.x/diesel/fn.sql_query.html) into something that implements `QueryableByName`. 

Closed as this is not a bug.

**Closed by weiznich** 2023-05-08 06:02 UTC
Labels: bug
