### ISSUE TITLE
Release with Diesel 2.2.1

### ISSUE THREAD

**Issue by willbuckner** [weiznich/diesel_async#162] opened 2024-07-02 19:39 UTC
I'm not sure what the normal release cadence is, but would it be possible to do a release soon with Diesel 2.2.1? There's a 2.2 feature we've been wanting to use, but we're stuck on 2.1. Thanks!

**Comment by weiznich** [comment] 2024-07-03 05:35
Releases a cut as soon as they are ready. As this is a free time project I generally do not give any ETA's for that other than when it's done. 
For the next release we would at least need to resolve #103 as blocking issue and likely we want to implement the necessary functions to support the new diesel `Instrumentation` interface for async connections as well. Your contributions are welcome to make this happen sooner, otherwise you just need to wait until someone has time to work on these points.

Closed as this is not a bug. (Also it does not follow the required issue template). Please fill future questions like that one as discussion.

**Closed by weiznich** 2024-07-03 05:35 UTC
Labels: bug

**Comment by willbuckner** [comment] 2024-07-03 06:17
Totally understand, thanks very much and I'm sorry for opening this discussion in the wrong place. I'd never used Discussions before but I see it now. I haven't had my head deep enough in Diesel's code to know what to do about #103, but I'll take a look and see if there's any other way I can contribute. No rush, thanks again for the response and your hard work on this project 🙏
