### ISSUE TITLE
RunQueryDsl overrides calls to vec.first() to RunQueryDsl::first()

### ISSUE THREAD

**Issue by cdxker** [weiznich/diesel_async#142] opened 2024-03-13 10:44 UTC
## Setup

RunQueryDsl overrides calls to vec.first to RunQueryDsl::first() this happens to all possible calls to first() if the trait is imported.

### Versions

- **Rust:**: 1.75
- **Diesel:**: 2.1.4
- **Diesel_async:**: 0.4.1
- **Database:**: None
- **Operating System**: EndeavourOS

### Feature Flags

- **diesel:**: None
- **diesel_async:**: None

## Problem Description

The `diesel_async::RunQueryDsl` trait overrides the default behavior of any structs `first()` function to RunQueryDsl::first causing a nasty compile time error.

### What are you trying to accomplish?

 I wish to use the vec.first() operation instead of vec.get(0). (Mainly becuase clippy errors, but this is a pretty hard bug to find).

### Steps to reproduce

Here is a gist that shows the issue at hand.
https://gist.github.com/fastfists/9d0f1da80f825be39f9a4499aa8990a7

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/weiznich/diesel_async/issues) for similar possible closed issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [X] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2024-03-13 10:50
Thanks for filling this bug report. I've changed it to be tracked as feature request, as it's strictly speaking not a bug. We are happy to receive a PR that improves this as long as it does not break existing code.

**Comment by fastfists** [comment] 2024-03-13 21:33
I tried reading into it but did not quite understand, how does the trait work at the current moment? Does it try to infer any `diesel::QueryDsl` functions into `diesel_async::RunQueryDsl` functions?

**Comment by weiznich** [comment] 2024-03-15 09:50
The relevant implementation is here: https://github.com/weiznich/diesel_async/blob/1ef43d2a8a4080c1e9e5c34056f4d26cbb2a85cc/src/run_query_dsl/mod.rs#L626-L637

That one essentially says that this method is only available for types that implement `LimitDsl`. That shouldn't be the case for `Vec<T>`, because that trait is only implemented for diesel query DSL structs. So I'm not sure why rustc believes that this could potentially overlap with the `first` method from `Vec<()>`, might be even worth filling an issue for that at the rust repo? (Feel free to ping me from there)

**Comment by fiadliel** [comment] 2024-06-19 07:07
As I understand it, the behavior of method resolution is that for a particular receiver type, the compiler looks first for inherent methods, and if that fails, then it looks for methods provided by visible traits (`RunQueryDsl` is visible if imported).

One might expect the inherent `first` method implemented by `Vec` to be chosen - BUT it is implemented for `&Vec`, whereas the extension method here is implemented for `Vec` (because of the `self` parameter).

As per https://doc.rust-lang.org/reference/expressions/method-call-expr.html, the algorithm is run in order for candidate receiver types, and `T` (aka `Vec`) has the highest priority.

**Comment by pdtilton** [comment] 2024-08-29 13:58
For anyone searching for a workaround you can use: `.nth(0)`.

**Comment by pdtilton** [comment] 2024-08-29 14:06
For those looking for a workaround you can use: `.get(0)`.

**Comment by weiznich** [comment] 2024-08-30 06:51
I think this is essentially another duplicate of https://github.com/rust-lang/rust/issues/127306.

Closed as this is an upstream rust bug.

**Closed by weiznich** 2024-08-30 06:51 UTC
Labels: enhancement
