### ISSUE TITLE
diesel_async  does not support sql_query (async)

### ISSUE THREAD

**Issue by rxdiscovery** [weiznich/diesel_async#148] opened 2024-05-01 04:14 UTC
Hello,

I would like to know if you plan to add the possibility of using sql_query in async?

Thank you in advance for your reply.

### Versions

- **Rust: 1.77.2**
- **Diesel: 2.1.6**
- **Diesel_async: 0.4.1**
- **Database: Postgres**
- **Operating System: Linux**

**Comment by omid** [comment] 2024-05-01 06:32
I use `sql_query` in a project and it works (with diesel_async 0.3)
I think you need to provide more details about how you use sql_query

**Comment by weiznich** [comment] 2024-05-03 09:38
Our tests use `sql_query` internally so it is supported (and that support is tested):

https://github.com/weiznich/diesel_async/blob/2a026c0c586117e5612bf6d80908051762c2991d/tests/lib.rs#L128

Closed as cannot reproduce. Feel free to provide a minimal reproducible example to get further support.

**Closed by weiznich** 2024-05-03 09:38 UTC
Labels: bug

**Comment by rxdiscovery** [comment] 2024-05-09 03:11
thank you very much, it was just a dependency problem  :+1:
