### ISSUE TITLE
Failed to find a type oid for ENUM_TYPE

### ISSUE THREAD

**Issue by omid** [weiznich/diesel_async#103] opened 2023-09-01 14:27 UTC
### Versions

- **Rust:** 1.72
- **Diesel:** 2.1
- **Diesel_async:** 0.4.1
- **Database:** postgresql
- **Operating System** linux

## Problem Description
After I upgrade the code from diesel-async 0.3.x to 0.4, I faced this error: `Failed to find a type oid for ENUM_TYPE`.
After I downgrade, the error disappeared. The only change in the code base was diesel-async version.

**Comment by weiznich** [comment] 2023-09-01 14:30
Can you please provide an reproducible example, otherwise this report is not actionable.

**Comment by omid** [comment] 2023-09-01 14:33
I tested it on a big project. 
I'll try to make a minimum code base next week 🙏

**Comment by omid** [comment] 2023-09-05 10:39
@weiznich, thanks. The problem is in `eq_any` (`eq` is fine). 
Within `custom_types_round_trip` test, this following code fails:
```
custom_types::table
        .filter(custom_types::custom_enum.eq_any([MyEnum::Foo]))
        .load(connection)
        .await
        .unwrap();
```

with this error:
```
thread 'custom_types::custom_types_round_trip' panicked at 'called `Result::unwrap()` on an `Err` value: SerializationError(FailedToLookupTypeError(PgMetadataCacheKey { schema: None, type_name: "my_type" }))'
```

**Comment by weiznich** [comment] 2023-09-06 16:43
Thanks for providing this example. I can reproduce the issue with that.

**Comment by neogenie** [comment] 2023-09-12 13:38
I confirm the bug is reproducible

**Comment by weiznich** [comment] 2023-09-12 18:11
The problematic code here is that one:

https://github.com/weiznich/diesel_async/blob/ec38eca3d7fccf4097fae20d655a26f11df015ee/src/pg/mod.rs#L319-L382

For custom types we need to resolve the type name to a oid, which might require executing a database query. I've choosen to delay resolving these oid's from the types names until we collected all bind parameters, but this has an important problem: Sometimes this oid is used during bind value serialization (for example for arrays: https://github.com/diesel-rs/diesel/blob/ac0b075f9ce297e06e8e728fce1573e7e1d8b797/diesel/src/pg/types/array.rs#L102) and then we don't get the serialized bind value at all, but an error message.

Now it's somewhat problematic to fix that because on the one hand we want to collect the bind parameters before entering the `async` below, to prefend a `Send` bound on the query generic type. On the other hand, we cannot execute queries outside an async block as executing a query requires resolving a future. I'm happy for suggestions on how to resolve that situation.

**Comment by formlogic-kirk** [comment] 2023-12-12 17:56
Attempted to port a decent-sized codebase over to `diesel_async`, and everything seems to have worked great except for this (which is pretty blocking). I'm not sure if I'll have time to try to come up with a solution or not yet, but wanted to at least report hitting it

**Comment by weiznich** [comment] 2023-12-15 12:49
It's on my list to address this at some point, but I cannot really make promises about the timeline. The problem is not that simple to solve is outlined in [this comment](https://github.com/weiznich/diesel_async/issues/103#issuecomment-1716200436). Essentially it boils down to the fact that we don't want/cannot have a `Send` bound on the query for reasons but that makes it harder to evaluate futures borrowing that type. In the end it's likely solvable by making the returned future conditional send based on the type parameters.

**Comment by weiznich** [comment] 2024-01-17 06:52
As a temporary workaround it should be possible to just have a query at connection setup that does use that enum type and doesn't use `.eq_any()`. That will prepopulate the cache and therefore workaround the cache miss in later queries. That's not a real solution but it should unblock any user that is affected by this bug.

**Comment by techtunde** [comment] 2024-01-30 01:49
> As a temporary workaround it should be possible to just have a query at connection setup that does use that enum type and doesn't use `.eq_any()`. That will prepopulate the cache and therefore workaround the cache miss in later queries. That's not a real solution but it should unblock any user that is affected by this bug.

Has anyone gotten this to work? If so can anyone provide an example of what this looks like, I tried doing the following without much luck.

```
sql_query("SELECT COUNT(*) from segment_features WHERE feature_type = $1")
 .bind::<sql_types::SegmentFeatureType, _>(feature)
 .await
 .context(format!("Failed to prefetch {feature}"))?;
```

**Comment by omid** [comment] 2024-01-30 07:48
> Has anyone gotten this to work? If so can anyone provide an example of what this looks like, I tried doing the following without much luck.
> 
> ```
> sql_query("SELECT COUNT(*) from segment_features WHERE feature_type = $1")
>  .bind::<sql_types::SegmentFeatureType, _>(feature)
>  .await
>  .context(format!("Failed to prefetch {feature}"))?;
> ```

I haven't tried that. Because I have many enum types and the query is generated dynamically, so the workaround doesn't make sense that much in my case.

But anyway, can you try a normal query with `.eq()`? I mean without `sql_query`. And generally `COUNT(*)` is slow-ish, better to return a row and `.limit(1)`.

**Comment by weiznich** [comment] 2024-02-02 13:18
@techtunde You are right, that also does not work. :(

**Comment by lsunsi** [comment] 2024-03-19 11:36
@weiznich I do not have enough knowledge about the codebase, but I'm seriously considering moving to diesel-async on my company's project (because we're hitting a limit on spawn-blocking approach for regular diesel).

We rely heavily on enums, so this issue is likely a blocker for us! I wanted to try and help tackling it, but I don't know where to start. Do you have an idea of implementation or even an indication of where I should start reading to understand the issue?

**Comment by omid** [comment] 2024-03-19 12:09
@lsunsi please ask your company to sponsor @weiznich to push this forward 🙏🏼 or do this yourself

**Comment by lsunsi** [comment] 2024-03-19 14:15
@omid This would be awesome and I'll pass this message along. In the in between, I might be able to help with some code myself, if that's useful for him or you. (:

**Comment by weiznich** [comment] 2024-03-19 18:12
@lsunsi See this post for a starting point: https://github.com/weiznich/diesel_async/issues/103#issuecomment-1716200436. I do not have a specific idea how to solve this yet.

**Comment by jun-sheaf** [comment] 2024-05-06 06:39
Instead of making resolving Oid's asynchronous, how about making it synchronous? This would only affect the performance of the initial query; every other query would have the same performance.

**Comment by weiznich** [comment] 2024-05-06 06:41
That's unfortunately no acceptable solution to the problem. If we have an async connection implementation it needs to be fully async, otherwise it's just not worth the trouble to maintain it at all.

**Comment by jun-sheaf** [comment] 2024-05-06 06:53
> That's unfortunately no acceptable solution to the problem. If we have an async connection implementation it needs to be fully async, otherwise it's just not worth the trouble to maintain it at all.

The connection doesn't need to be blocking. We just need to conditionally do a spawn_blocking with the underlying engine.

**Comment by weiznich** [comment] 2024-05-06 06:54
That's unfortunately not possible as the `spawn_blocking` requires a `Send` bound on all arguments and some of them are not `Send`.

**Comment by lsunsi** [comment] 2024-05-06 10:39
Moreover I share the perception that it'd be surprising to see an spawn_blocking (wherever it is) in the async implementation, it'd have to always be cited as an "exception" to the async model.

**Comment by DontBreakAlex** [comment] 2024-05-21 09:44
I'm also hitting this issue. Is there a way to specify the oid manually ? We can always get it dynamically beforehand with `SELECT 'my_type'::regclass::oid;`

I'm using a custom composite type and not an enum but I don't think this makes a difference.
```Rust
#[derive(SqlType)]
#[derive(QueryId)]
#[diesel(postgres_type(name = "my_type"))]
pub struct MyType;
```

**Comment by LorenzSchueler** [comment] 2024-05-21 11:24
> As a temporary workaround it should be possible to just have a query at connection setup that does use that enum type and doesn't use `.eq_any()`. That will prepopulate the cache and therefore workaround the cache miss in later queries. That's not a real solution but it should unblock any user that is affected by this bug.

@weiznich Wouldn't it be possible to look up all oid's of enums at startup and put them in the cache so that they don't have to be resolved when encountered for the first time?
Something like: `select oid, typname from pg_type where pg_type.oid = any (select enumtypid from pg_enum);` ?

**Comment by weiznich** [comment] 2024-05-21 17:12
@DontBreakAlex There is no known workaround yet as already written above. Asking that again does likely not change anything, at least other than binding time that could be used to work on a solution.

@LorenzSchueler I remember that I tried that at some point, but it did not work in certain cases. If you create the enum after you established the connection for example, which is quite common if you run migrations from your application. The other disadvantage is this is a quite large amount of data. There are 699 entries in my local `pg_type` table. We would need to load them all, as we need to support other types than enums as well.

**Comment by weiznich** [comment] 2024-06-05 19:12
We generally use the binary protocol for all bind values because that decouples the values from the query, which in turn allows us not to care about possible injections. It also gives us better performance as the binary representation is usually smaller.

**Comment by omid** [comment] 2024-06-06 07:45
@weiznich thanks. Another question, somewhere in the [code](https://github.com/weiznich/diesel_async/blob/ec38eca3d7fccf4097fae20d655a26f11df015ee/src/pg/mod.rs#L319-L382) comments, you mentioned: `We apply this workaround to prevent requiring all the diesel serialization code to be async`.
What's the problem, to run it in async?

**Comment by weiznich** [comment] 2024-06-06 13:20
> Another question, somewhere in the [code](https://github.com/weiznich/diesel_async/blob/ec38eca3d7fccf4097fae20d655a26f11df015ee/src/pg/mod.rs#L319-L382) comments, you mentioned: We apply this workaround to prevent requiring all the diesel serialization code to be async.
What's the problem, to run it in async?

The problem would be that the `Pg::metadata` function would need to return a future if we would execute an async query inside that function. That in turn would need `ToSql::to_sql` would need to return a future as well, which in turn would be either:

* A breaking change to diesel itself (and problematic there, because what would we do with futures there?)
* Disallow reusing the serialization code from diesel, which in turn would make diesel_async incompatible with the existing diesel ecosystem.

> What will be the problem to not prevent a Send bound on the query generic type?

That likely would break the [`AsyncConnectionWrapper` ](https://docs.rs/diesel-async/latest/diesel_async/async_connection_wrapper/type.AsyncConnectionWrapper.html), as we don't have a `+Send` bound on the [`LoadConnection::load`](https://docs.diesel.rs/master/diesel/connection/trait.LoadConnection.html#tymethod.load) impl in diesel itself, as opposed to what we had on the [`AsyncConnection::load` impl in diesel_async 0.3](https://docs.rs/diesel-async/0.3.2/src/diesel_async/lib.rs.html#323). Otherwise it would be "simple" to just perform the lookup queries while serializing the results, but that's not possible, because as soon as we `.await` and still hold any reference to the query we would need that `Send` bound there.

**Closed** 2024-07-19 08:56 UTC
Labels: bug

**Comment by omid** [comment] 2024-07-19 08:59
No way... Thanks @weiznich and @dullbananas. You are great <3
