### ISSUE TITLE
0.4.x doesn't work with custom types

### ISSUE THREAD

**Issue by inferiorhumanorgans** [weiznich/diesel_async#144] opened 2024-03-25 08:45 UTC
OID lookup is broken – `lookup_type` just returns an error vs 0.3.x where it called the lookup function.

**Comment by weiznich** [comment] 2024-03-25 08:47
Duplicate of https://github.com/weiznich/diesel_async/issues/103 + this does not follow the required bug template

**Closed by weiznich** 2024-03-25 08:47 UTC
Labels: bug
