### ISSUE TITLE
PostgreSQL TLS should be much more straightforward

### ISSUE THREAD

**Issue by vriesk** [weiznich/diesel_async#191] opened 2024-09-19 12:53 UTC
### Versions

- **Rust:** irrelevant
- **Diesel:** irrelevant
- **Diesel_async:** 0.5
- **Database:** PostgreSQL
- **Operating System** irrelevant

### Feature Flags

- **diesel:** irrelevant
- **diesel_async:** `postgresql`

## Problem Description

Right now, adding TLS support to `diesel-async`-provided `AsyncPgConnection` is clunky at best, requiring a deep dive into `tokio-postgres`, `tokio-postgres-rustls` and `rustls` directly, along with root CA crates (optionally).

In addition, it requires to use the low-lever `tokio-postgress` connection API that needs a `tokio::spawn`, which really should not be like that in any high-level app code.

## What I would like to see

A simple toggle for TLS support provided with `AsyncPgConnection`'s `establish()` (or similar) method, optionally accepting custom `rustls::RootCertStore` object, and defaulting to feature-flag controlled WEBPKI or "native" one. Alternatively, the `RootCertStore` argument might be required, making the user control the lifetime of the cert store, as building it, in particular from the native certs residing in a filesystem, is rather heavy.

Would you be willing to accept a PR that achieves this?

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/weiznich/diesel_async/issues) for similar possible closed issues.
 
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment] 2024-09-19 13:04
Duplicate of https://github.com/weiznich/diesel_async/discussions/184.

Additionally that's not a bug report but a feature request, so I'm closing this in favor of the existing discussion.

**Closed by weiznich** 2024-09-19 13:04 UTC
Labels: bug

**Comment by vriesk** [comment] 2024-09-19 16:15
Apologies, I haven't noticed that feature requests are in the Discussions tab.
